apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-06-09T01:25:43Z
  labels:
    app: rancher-catalog
    name: rancher-catalog
  name: rancher-catalog
spec:
  replicas: 1
  selector:
    name: rancher-catalog
  template:
    metadata:
      creationTimestamp: 2016-06-09T01:25:43Z
      labels:
        app: rancher-catalog
        name: rancher-catalog
      name: rancher-catalog
    spec:
      containers:
      - image: tangfeixiong/rancher-catalog-service
        imagePullPolicy: Always
        name: rancher-catalog
        ports:
        - containerPort: 8088
          protocol: TCP
        resources:
          requests:
            cpu: "0"
            memory: "0"
        # volumeMounts:
        # - mountPath: /tmp/cloned-catalog
        #   name: data
      serviceAccountName: ""
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: data
      # - emptyDir: {}
      #   name: data1
      # - hostPath:
      #     path: /mnt/hostpath1
      #   name: data2
      # - name: data3
      #   nfs:
      #     server: 10.0.0.1
      #     path: /mnt/nfs1
      #     readOnly: false
