apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher-catalog
    heritage: harpoon
    name: rancher-catalog
    vendor: qingyuanos.io
  name: rancher-catalog
  namespace: helm
spec:
  type: NodePort
  ports:
  - name: resthttp
    nodePort: 32127
    port: 8088
    protocol: TCP
  selector:
    name: rancher-catalog
