apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-06-09T01:25:43Z
  name: rancher-catalog
  namespace: helm
  labels:
    app: rancher-catalog
    heritage: harpoon
    name: rancher-catalog
    vendor: qingyuanos.io
spec:
  replicas: 1
  selector:
    name: rancher-catalog
  template:
    metadata:
      creationTimestamp: 2016-06-09T01:25:43Z
      name: rancher-catalog
      namespace: helm
      labels:
        app: rancher-catalog
        heritage: helm
        name: rancher-catalog
        vendor: qingyuanos.io
    spec:
      containers:
      - name: rancher-catalog
        image: tangfeixiong/rancher-catalog-service:0.6.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
          protocol: TCP
        resources:
          requests:
            cpu: "0"
            memory: "0"
        # volumeMounts:
        # - mountPath: /tmp/cloned-catalog
        #   name: data
      serviceAccountName: ""
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: data
      # - emptyDir: {}
      #   name: data1
      # - hostPath:
      #     path: /mnt/hostpath1
      #   name: data2
      # - name: data3
      #   nfs:
      #     server: 10.0.0.1
      #     path: /mnt/nfs1
      #     readOnly: false
